// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurveyDeserialise.SurveyDetails;

namespace SurveyDeserialise.Migrations
{
    [DbContext(typeof(SurveyDbContext))]
    partial class SurveyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SurveyDeserialise.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("AnswerId");

                    b.Property<int>("AnswerType");

                    b.Property<string>("CategoryTexts");

                    b.Property<int>("ItemType");

                    b.Property<int>("OrderNumber");

                    b.HasKey("AnswerId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SurveyDeserialise.Entities.QuestionnaireEntity", b =>
                {
                    b.Property<int>("SubjectId");

                    b.Property<int>("ItemType");

                    b.Property<int>("OrderNumber");

                    b.Property<string>("QuestionnaireText");

                    b.HasKey("SubjectId");

                    b.ToTable("Questionnaire");
                });

            modelBuilder.Entity("SurveyDeserialise.Entities.QuestionnaireItemEntity", b =>
                {
                    b.Property<int>("QuestionId");

                    b.Property<int>("AnswerCategoryType");

                    b.Property<int>("ItemType");

                    b.Property<int>("OrderNumber");

                    b.Property<string>("QuestionnaireItemText");

                    b.HasKey("QuestionId");

                    b.ToTable("QuestionnaireItem");
                });
#pragma warning restore 612, 618
        }
    }
}
